default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kcsc_api_development

test:
  <<: *default
  database: kcsc_api_test

production:
  <<: *default
  database: kcsc_api_production
  username: kcsc_api
  password: <%= ENV['KCSC_API_API_DATABASE_PASSWORD'] %>
